"""Initial Schema Filtered

Revision ID: 7de0146ce13b
Revises: 
Create Date: 2026-03-25 15:40:03.856896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de0146ce13b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'first_name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'last_name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'auth_method',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'session_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'org_name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=True,
               schema='securesphere')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'org_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'session_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'auth_method',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True,
               schema='securesphere')
    op.alter_column('audit_events', 'first_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True,
               schema='securesphere')
    # ### end Alembic commands ###
